# Generated by Django 6.0.2 on 2026-02-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_id_alter_userlikelist_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_onboarding_completed',
            field=models.BooleanField(default=False),
        ),
    ]
