# Generated by Django 5.2.11 on 2026-02-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movie_id",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("title", models.CharField(max_length=200)),
                ("youtube_key", models.CharField(blank=True, max_length=50)),
                ("embed_url", models.URLField(blank=True, max_length=500)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("vote_average", models.FloatField(default=0)),
                ("star_rating", models.FloatField(default=0)),
                ("ott_providers", models.JSONField(blank=True, default=list)),
                ("is_in_theaters", models.BooleanField(default=False)),
                ("overview", models.TextField(blank=True)),
                ("poster_path", models.URLField(blank=True, max_length=500)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("like_count", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "genres",
                    models.ManyToManyField(
                        blank=True, related_name="movies", to="movies.genre"
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
