# Generated by Django 6.0.2 on 2026-02-11 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre_key', models.CharField(blank=True, help_text='유저의 pref_... 장르 필드와 매칭되는 키 (예: action, comedy)', max_length=50, null=True)),
                ('base_score', models.FloatField(default=0, help_text='이 카테고리 내 영화들의 평균 점수 (디폴트 정렬용)')),
                ('movies', models.ManyToManyField(related_name='home_categories', to='movies.movie')),
            ],
        ),
    ]
