# Generated by Django 6.0.2 on 2026-02-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecategory',
            name='category_type',
            field=models.CharField(default='general', help_text='special 또는 general', max_length=20),
        ),
        migrations.AlterField(
            model_name='homecategory',
            name='base_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='homecategory',
            name='genre_key',
            field=models.CharField(blank=True, help_text="장르 이름들을 '|'로 연결 (예: 액션|코미디)", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homecategory',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
